Facade table improvements
PhpGt/Dom pull request #273
Opened 2021-04-08 11:08 UTC by g105b

Hi @speich ,

Please see these minor changes I've made to the HTMLTableElement tests. I'd like to hear your feedback.

Cheers,
Greg.

2021-04-16 07:18 UTC, speich commented
Sorry for the silence. I'll have a look this weekend.

2021-04-16 10:39 UTC, g105b commented
No rush! Take you time, I've still a few classes to complete coding before the facade will be released.

2021-04-17 17:00 UTC, speich commented on src/HTMLElement/HTMLTableElement.php
>  				$name = strtolower($row->parentNode->nodeName);
I would move this line now to line 318 just before the switch statement

2021-04-17 17:02 UTC, speich requested changes
I would make a tiny change, see inline comment

2021-04-17 18:25 UTC, merged

2021-04-17 18:25 UTC, g105b commented
Thanks @speich - nearly there now!